### PR TITLE
Initializing the project

### PR DESCRIPTION
**Pull request by ahmedhindawi**

### CODE REVIEW

**Comment by mhmadalaa** [comment]
I just add `.placeholder` empty file to let git track and push empty directories to github, so when someone start working in any directory feel free to just remove the file

**Review by mhmadalaa — APPROVED** [review]
I totally trust myself lol

**Comment by mhmadalaa** [comment]
something to mention that there is another criterias to follow in structuring the project as a case 
```
src/
├── auth
│   ├── controller.js
│   ├── middleware.js
│   ├── model.js
│   └── router.js
├── books
│   ├── controller.js
│   ├── middleware.js
│   ├── model.js
│   └── router.js
└── users
    ├── controller.js
    ├── middleware.js
    ├── model.js
    └── router.js
```

**Comment by ahmedhindawi** [comment]
> I just add `.placeholder` empty file to let git track and push empty directories to github, so when someone start working in any directory feel free to just remove the file

add this to `docs/structure.md`

**Comment by ahmedhindawi** [comment]
> something to mention that there is another criterias to follow in structuring the project as a case
> 
> ```
> src/
> ├── auth
> │   ├── controller.js
> │   ├── middleware.js
> │   ├── model.js
> │   └── router.js
> ├── books
> │   ├── controller.js
> │   ├── middleware.js
> │   ├── model.js
> │   └── router.js
> └── users
>     ├── controller.js
>     ├── middleware.js
>     ├── model.js
>     └── router.js
> ```

this too

**Comment by mhmadalaa** [comment]
> > I just add `.placeholder` empty file to let git track and push empty directories to github, so when someone start working in any directory feel free to just remove the file
> 
> add this to `docs/structure.md`

ok got it

**Review by Nayra000 — APPROVED** [review]

**Pull request merged**
